package internal

type Category struct {
	MimeTypes  []string
	Extensions []string
}

var Categories = map[string]Category{
	"Archives": {
		MimeTypes: []string{
			"application/zip",
			"application/x-tar",
			"application/gzip",
			"application/x-7z-compressed",
			"appliction/vnd.rar",
			"application/x-bzip",
			"application/x-bzip2",
		},
		Extensions: []string{
			".zip",
			".tar",
			".gz",
			".tgz",
			".xz",
			".lzma",
			".7z",
			".bz",
			".bz2",
			".img",
			".iso",
			".dmg",
		},
	},
	"Images": {
		MimeTypes: []string{
			"image/jpeg",
			"image/png",
			"image/gif",
			"image/webp",
			"image/avif",
			"image/bmp",
		},
		Extensions: []string{
			".png",
			".jpeg",
			".jpg",
			".gif",
			".avif",
			".bmp",
			".tiff",
		},
	},
	"Audio": {
		MimeTypes: []string{
			"audio/mpeg",
			"audio/wav",
			"audio/ogg",
			"audio/midi",
			"audio/webm",
		},
		Extensions: []string{
			".mp3",
			".wav",
			".weba",
			".ogg",
			".mid",
			".midi",
			".m4a",
			".heic",
		},
	},
	"Video": {
		MimeTypes: []string{
			"video/mp4",
			"video/x-matroska",
			"video/webm",
			"video/x-msvideo",
		},
		Extensions: []string{
			".mp4",
			".mov",
			".webm",
			".wmv",
			".mkv",
		},
	},
	"Documents": {
		MimeTypes: []string{
			"application/pdf",
			"text/plain",
			"text/markdown",
			"application/vnd.oasis.opendocument.presentation",
			"application/vnd.oasis.opendocument.spreadsheet",
			"application/vnd.oasis.opendocument.text",
			"application/epub+zip",
			"text/calendar",
			"application/rtf",
			"application/vnd.ms-excel",
			"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
			"application/xml",
			"application/vnd.amazon.ebook",
			"text/csv",
			"application/msword",
			"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		},
		Extensions: []string{
			".pdf",
			".typ",
			".txt",
			".md",
			".odp",
			".ods",
			".odt",
			".epub",
			".ical",
			".rtf",
			".xls",
			".xlsx",
			".azw",
			".csv",
			".tsv",
			".doc",
			".docx",
			".ppt",
			".pptx",
		},
	},
	"Code": {
		MimeTypes: []string{
			"text/javascript",
			"application/json",
			"application/x-httpd-php",
			"text/html",
			"application/x-sh",
			"text/css",
		},
		Extensions: []string{
			".js",
			".ts",
			".json",
			".php",
			".html",
			".css",
			".sh",
			".nu",
			".bat",
			".ps1",
			".rb",
			".rs",
			".go",
			".jl",
			".lua",
			".c",
			".cc",
			".h",
			".hh",
			".cpp",
			".hpp",
		},
	},
}
