package internal

var Categories = map[string][]string{
	"Archives": {
		"application/zip",
		"application/x-tar",
		"application/gzip",
		"application/x-7z-compressed",
		"appliction/vnd.rar",
		"application/x-bzip",
		"application/x-bzip2",
	},
	"Images": {
		"image/jpeg",
		"image/png",
		"image/gif",
		"image/webp",
		"image/avif",
		"image/bmp",
	},
	"Audio": {
		"audio/mpeg",
		"audio/wav",
		"audio/ogg",
		"audio/midi",
		"audio/webm",
	},
	"Video": {
		"video/mp4",
		"video/x-matroska",
		"video/webm",
		"video/x-msvideo",
	},
	"Documents": {
		"application/pdf",
		"text/plain",
		"text/markdown",
		"application/vnd.oasis.opendocument.presentation",
		"application/vnd.oasis.opendocument.spreadsheet",
		"application/vnd.oasis.opendocument.text",
		"application/epub+zip",
		"text/calendar",
		"application/rtf",
		"application/vnd.ms-excel",
		"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		"application/xml",
		"application/vnd.amazon.ebook",
		"text/csv",
		"application/msword",
		"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	},
	"Code": {
		"text/javascript",
		"application/json",
		"application/x-httpd-php",
		"text/html",
		"application/x-sh",
		"text/css",
	},
}
